### ISSUE TITLE
linking with `D:\substrate-sdk-android\build\linker-wrapper\linker-wrapper.bat` failed: exit code: 9009

### ISSUE THREAD

**Issue by DannyAhmedApex** [novasamatech/substrate-sdk-android#57]
Hi I have been struggling from last week I could not build this sdk.

could not compile `sr25519java` due to previous error; 26 warnings emitted

  Compiling cfg-if v1.0.0
   Compiling byteorder v1.4.3
   Compiling byte-tools v0.3.1
   Compiling ppv-lite86 v0.2.17
   Compiling opaque-debug v0.2.3
   Compiling bytes v1.4.0
   Compiling subtle v2.5.0
   Compiling fake-simd v0.1.2
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-linux-android` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-linux-android`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: cannot find macro `assert` in this scope
 --> C:\Users\Daniel Ahmed\.cargo\registry\src\github.com-1ecc6299db9ec823\byte-tools-0.3.1\src\lib.rs:9:5
  |
9 |     assert!(dst.len() >= src.len());

**Comment by DannyAhmedApex** [comment]
Can you please help in building this SDK. I am looking for one small change as Our current substrate based blockchain rpc call return response in a way where error message lies in data field instead of message

Current RpcResponse , Error class has only two field code, message so what I am looking for data field

**Comment by valentunn** [comment]
Hey, you should execute 

``` bash
rustup target add armv7-linux-androideabi && \
    rustup target add i686-linux-android && \
    rustup target add aarch64-linux-android && \
    rustup target add x86_64-linux-android
```

**Comment by DannyAhmedApex** [comment]
For the reference I did above commands and you can check the status below

```
PS D:\substrate-sdk-android> rustup target add armv7-linux-androideabi
info: component 'rust-std' for target 'armv7-linux-androideabi' is up to date
PS D:\substrate-sdk-android> rustup target add i686-linux-android
info: component 'rust-std' for target 'i686-linux-android' is up to date
PS D:\substrate-sdk-android> rustup target add aarch64-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
PS D:\substrate-sdk-android> rustup target add x86_64-linux-android
info: component 'rust-std' for target 'x86_64-linux-android' is up to date
PS D:\substrate-sdk-android> 
```

Rust and python are installed and configured well in the system.

**Comment by DannyAhmedApex** [comment]
#Hi update: I resolved that long lansting issue:

**I removed the**  
`crate-type = ["cdylib"] from Cargo.toml file. I get that sense from this` [link](https://github.com/mozilla/rust-android-gradle/issues/76#issuecomment-969152107) 

After I get rid of substrate-sdk-android\build\linker-wrapper\linker-wrapper.bat

**then was facing another issue:**

` Failed to calculate the value of task ':fearless-utils:compileDebugJavaWithJavac' property 'options.generatedSourceOutputDirectory'`

**I upgraded the gradle plugin to**   `classpath 'com.android.tools.build:gradle:4.2.2'`

Now the project is running with me.
