### ISSUE TITLE
DictEnum$Entry@22d9546 (Entry) is not a valid instance of 127

### ISSUE THREAD

**Issue by efeint01** [novasamatech/substrate-sdk-android#88]
I'm trying to convert exact kotlin example to java, But getting DictEnum error `(Entry) is not a valid instance of 127` when calling coroutines (It's working on Kotlin)

Java Version:

```
// Create an instance of DictEnum.Entry
DictEnum.Entry<Object> destEntry = new DictEnum.Entry<>("Id", SS58Encoder.INSTANCE.decode("5H9YPS9FJX6nbFXkm9zVhoySJBX9RRfWF36abisNz5Ps9YaX"));
// Create the arguments map
Map<String, Object> arguments = new HashMap<>();
arguments.put("dest", destEntry);
arguments.put("value", BigInteger.ONE); // Using BigInteger.ONE for 1.toBigInteger()
extrinsicBuilder.call("Balances", "transfer", arguments);
CompletableFuture<String> extrinsic = FutureKt.future(
        CoroutineScopeKt.CoroutineScope(EmptyCoroutineContext.INSTANCE),
        EmptyCoroutineContext.INSTANCE,
        CoroutineStart.DEFAULT,
        (scope, continuation) -> extrinsicBuilder.build(BatchMode.BATCH, continuation));
// Handle the result or exception using exceptionally and thenAccept
extrinsic.exceptionally(e -> {
    // Handle exceptions that occurred during the suspend function execution
    System.err.println("Exception occurred: " + e.getMessage());
    return null; // Return a default value or null if needed
})
.thenAccept(result -> {
    if (result != null) {
        // Process the result if it's not null
        System.out.println("Suspend function result: " + result);
    } else {
        // Handle the case where the result is null or default
        System.out.println("Suspend function returned null or default value.");
    }
});

```

Kotlin Version:

```
    extBuilder.call(
        moduleName = "Balances",
        callName = "transfer",
        arguments = mapOf(
            "dest" to DictEnum.Entry(
                name = "Id",
                value = SS58Encoder.decode("5H9YPS9FJX6nbFXkm9zVhoySJBX9RRfWF36abisNz5Ps9YaX")
            ),
            "value" to 1.toBigInteger()
        )
    )


    val extrinsic = extBuilder.build()
```

Full error in java: `Exception occurred: io.novasama.substrate_sdk_android.runtime.definitions.types.composite.DictEnum$Entry@22d9546 (Entry) is not a valid instance of 127
`

**Comment by valentunn** [comment]
1. The library is not really intended nor tested for use with Java
2. The error is not related to coroutines but rather to type mismatch between expected and actual payload received for encoding. Please check for which argument `isValidInstance` check fails inside `GenericCall` and `DictEnum.Entry`

**Comment by vitadu** [comment]
// Create an instance of DictEnum.Entry
DictEnum.Entry<Object> destEntry = new DictEnum.Entry<>("Id", SS58Encoder.INSTANCE.decode("5H9YPS9FJX6nbFXkm9zVhoySJBX9RRfWF36abisNz5Ps9YaX"));
// Create the arguments map
Map<String, Object> arguments = new HashMap<>();
arguments.put("dest", destEntry);
arguments.put("value", BigInteger.ONE); // Using BigInteger.ONE for 1.toBigInteger()
extrinsicBuilder.call("Balances", "transfer", arguments);
CompletableFuture<String> extrinsic = FutureKt.future(
        CoroutineScopeKt.CoroutineScope(EmptyCoroutineContext.INSTANCE),
        EmptyCoroutineContext.INSTANCE,
        CoroutineStart.DEFAULT,
        (scope, continuation) -> extrinsicBuilder.build(BatchMode.BATCH, continuation));
// Handle the result or exception using exceptionally and thenAccept
extrinsic.exceptionally(e -> {
    // Handle exceptions that occurred during the suspend function execution
    System.err.println("Exception occurred: " + e.getMessage());
    return null; // Return a default value or null if needed
})
.thenAccept(result -> {
    if (result != null) {
        // Process the result if it's not null
        System.out.println("Suspend function result: " + result);
    } else {
        // Handle the case where the result is null or default
        System.out.println("Suspend function returned null or default value.");
    }
});
